global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-opentelemetry-collector:8889' ]  # Scrape from the OTLP Collector's Prometheus exporter
