receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4316"
      http:
        endpoint: "0.0.0.0:4317"
processors:
  batch:
exporters:
  #  prometheus:
  #    endpoint: "0.0.0.0:9091"
  prometheusremotewrite:
    endpoint: "http://victoria-metrics:8428/api/v1/write"
#  oltphttp/victoriametrics:
#    metrics_endpoint: "http://victoria-metrics:8428/api/v1/write"

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheusremotewrite ]
