receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4316"
      http:
        endpoint: "0.0.0.0:4317"
processors:
  deltatocumulative:
    max_stale: 5m
exporters:
  #  prometheus:
  #    endpoint: "0.0.0.0:9091"
  otlphttp/victoriametrics:
    metrics_endpoint: "http://victoria-metrics:8428/opentelemetry/v1/metrics"
#    endpoint: "http://victoria-metrics:8428/opentelemetry/v1/metrics"
#  oltphttp/victoriametrics:
#    metrics_endpoint: "http://victoria-metrics:8428/api/v1/write"

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ deltatocumulative ]
      exporters: [ otlphttp/victoriametrics ]