receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4316"
      http:
        endpoint: "0.0.0.0:4317"
processors:
  batch:
exporters:
  prometheus:
    endpoint: "0.0.0.0:9091"

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]
