apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: my-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
        - name: my-go-app
          image: hoanghs120/my-go-app:latest
          ports:
            - containerPort: 9000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-opentelemetry-collector.log.svc.cluster.local:4318"
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: my-go-app-service
spec:
  type: NodePort
  selector:
    app: my-go-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30123  # NodePort range is 30000-32767